Metrics/LineLength:
  Max: 99

Metrics/MethodLength:
  Max: 12

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassVars:
  Enabled: false
